### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by mathieujobin** [keylimetoolbox/redis_set_store#1]
Hey,

I was reading this https://ballardhack.wordpress.com/2013/04/25/we-fixed-rails-redis-store-to-rapidly-expire-50000-keys-daily-from-a-3-5m-key-cache/

and I wondered if you had publish your updated RedisStore

found this project but looks empty.

would be great to have your findings shipped as a gem 

thanks

**Comment by jeremywadsack** [comment]
@mathieujobin: We haven't extracted it yet, but I'll see if we can find time to do that. I wasn't sure how much interested there was in this beyond our own use case.

**Comment by jeremywadsack** [comment]
@mathieujobin sorry for the long delay, but finally extracted it: fb498ed
